# Generated by Django 4.0.3 on 2022-04-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0002_alumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
