# Generated by Django 4.0.3 on 2022-04-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0003_alumno_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='folleto',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
