# Generated by Django 4.0.3 on 2022-04-12 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0004_alumno_folleto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Nivel_Inicial',
        ),
        migrations.DeleteModel(
            name='Primaria',
        ),
        migrations.DeleteModel(
            name='Secundaria',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='email',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='folleto',
        ),
    ]
