# Generated by Django 4.0.3 on 2022-04-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0006_profesores_disciplina_profesores_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesores',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='avatar'),
        ),
    ]
