# Generated by Django 4.0.3 on 2022-04-13 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indice', '0002_avatar_delete_miuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
